CATEGORIES = {
    "🎬 Filmy & Seriály": [
        "Titanic",
        "Avatar",
        "Harry Potter",
        "Hra o tróny",
        "Shrek",
        "Lev kráľ",
        "Spiderman",
        "Batman",
        "Joker",
        "Inception",
        "Interstellar",
        "Squid Game",
        "Stranger Things",
        "Breaking Bad",
        "Frozen",
        "Piráti z Karibiku",
        "Pán prsteňov",
        "La La Land",
        "Forrest Gump",
        "The Office",
        "Friends",
        "Peaky Blinders",
        "Money Heist",
        "Wednesday",
        "Ted Lasso",
        "Succession",
        "The Crown",
        "Black Mirror",
        "Narcos",
        "Mandalorian",
        "Top Gun",
        "Gladiátor",
        "Matrix",
        "Jurassic Park",
        "Hviezdne vojny",
        "Avengers",
        "Muž so železnou maskou",
        "Bohemian Rhapsody",
        "Elvis",
        "Barbie",
        "Oppenheimer",
        "Dune",
        "Everything Everywhere All at Once",
        "No Country for Old Men",
        "The Godfather",
        "Pulp Fiction",
        "Fight Club",
        "The Shawshank Redemption",
        "Schindler's List",
        "Goodfellas",
        "The Dark Knight",
        "Silence of the Lambs",
        "American Beauty",
        "Cast Away",
        "The Truman Show",
        "Catch Me If You Can",
        "A Beautiful Mind",
        "Rain Man",
        "Home Alone",
        "Elf",
        "Die Hard",
        "Terminator",
        "Alien",
        "Jaws",
        "Back to the Future",
        "E.T.",
        "Indiana Jones",
        "Rocky",
        "Dirty Dancing",
        "Pretty Woman",
        "Grease",
        "Mamma Mia",
        "Chicago",
        "Les Misérables",
        "Moulin Rouge",
        "The Grand Budapest Hotel",
        "Wes Anderson",
        "Parasite",
        "Amélie",
        "Pan's Labyrinth",
        "Life is Beautiful",
        "Cinema Paradiso",
        "Spirited Away",
        "Princess Mononoke",
        "Your Name",
        "Akira",
        "Cowboy Bebop",
        "Death Note",
        "Attack on Titan",
        "Demon Slayer",
        "One Piece",
        "Naruto",
        "Dragon Ball",
        "Pokémon",
        "The Simpsons",
        "Family Guy",
        "South Park",
        "Futurama",
        "Rick and Morty",
        "BoJack Horseman",
        "Arcane",
        "The Witcher",
        "Bridgerton",
        "Euphoria",
        "White Lotus",
        "Yellowstone",
        "Ozark",
        "Mindhunter",
        "House of Cards",
        "Homeland",
        "24",
        "Lost",
        "Prison Break",
        "Grey's Anatomy",
        "House M.D.",
        "Scrubs",
        "ER",
        "How I Met Your Mother",
        "Big Bang Theory",
        "Two and a Half Men",
        "Seinfeld",
        "Curb Your Enthusiasm",
        "Fleabag",
        "Chernobyl",
        "Band of Brothers",
        "The Pacific",
        "True Detective",
        "Sharp Objects",
        "Mare of Easttown",
        "Broadchurch",
        "Years and Years",
        "The Handmaid's Tale",
        "Westworld",
        "Dark",
        "Severance",
        "The Bear",
        "Beef",
        "Abbott Elementary",
        "Only Murders in the Building",
        "Emily in Paris",
        "Sex and the City",
        "Desperate Housewives",
        "Downton Abbey",
        "Outlander",
        "Vikings",
        "Spartacus",
        "Rome",
        "Medici",
        "The Last Kingdom",
        "Knives Out",
        "Glass Onion",
        "Get Out",
        "Us",
        "Nope",
        "Everything Everywhere",
        "The Menu",
        "Triangle of Sadness",
        "Tár",
        "Women Talking",
        "The Whale",
        "Banshees of Inisherin"
    ],
    "🌍 Celebrities": [
        "Elon Musk",
        "Beyoncé",
        "Taylor Swift",
        "Cristiano Ronaldo",
        "Lionel Messi",
        "Kim Kardashian",
        "Rihanna",
        "Billie Eilish",
        "Justin Bieber",
        "Adele",
        "Lady Gaga",
        "Drake",
        "Eminem",
        "Will Smith",
        "Leonardo DiCaprio",
        "Angelina Jolie",
        "Dwayne Johnson",
        "Ariana Grande",
        "Ed Sheeran",
        "Shakira",
        "Zendaya",
        "Harry Styles",
        "Bad Bunny",
        "Cardi B",
        "Jeff Bezos",
        "Bill Gates",
        "Mark Zuckerberg",
        "Steve Jobs",
        "Barack Obama",
        "Oprah Winfrey",
        "Ellen DeGeneres",
        "Keanu Reeves",
        "Tom Hanks",
        "Meryl Streep",
        "Ryan Reynolds",
        "Jennifer Aniston",
        "Brad Pitt",
        "Scarlett Johansson",
        "Margot Robbie",
        "Timothée Chalamet",
        "Kylie Jenner",
        "Selena Gomez",
        "Dua Lipa",
        "Olivia Rodrigo",
        "Sabrina Carpenter",
        "Charli XCX",
        "SZA",
        "Lizzo",
        "Doja Cat",
        "Nicki Minaj",
        "Celine Dion",
        "Britney Spears",
        "Christina Aguilera",
        "Jennifer Lopez",
        "Katy Perry",
        "Miley Cyrus",
        "Pink",
        "Gwen Stefani",
        "Amy Winehouse",
        "Lana Del Rey",
        "Lorde",
        "Halsey",
        "Meghan Trainor",
        "Sia",
        "Florence Welch",
        "Bruno Mars",
        "The Weeknd",
        "Post Malone",
        "Travis Scott",
        "Kendrick Lamar",
        "Jay-Z",
        "Kanye West",
        "Lil Wayne",
        "Snoop Dogg",
        "Ice Cube",
        "Tupac",
        "Notorious B.I.G.",
        "Chris Brown",
        "Usher",
        "Ne-Yo",
        "John Legend",
        "Sam Smith",
        "Shawn Mendes",
        "Niall Horan",
        "Louis Tomlinson",
        "Zayn Malik",
        "Liam Payne",
        "One Direction",
        "BTS",
        "Blackpink",
        "Stray Kids",
        "NewJeans",
        "TWICE",
        "Tom Cruise",
        "Johnny Depp",
        "Robert Downey Jr.",
        "Chris Evans",
        "Chris Hemsworth",
        "Mark Ruffalo",
        "Jeremy Renner",
        "Cate Blanchett",
        "Natalie Portman",
        "Emma Stone",
        "Emma Watson",
        "Jennifer Lawrence",
        "Anne Hathaway",
        "Reese Witherspoon",
        "Viola Davis",
        "Lupita Nyong'o",
        "Halle Berry",
        "Whoopi Goldberg",
        "Denzel Washington",
        "Morgan Freeman",
        "Samuel L. Jackson",
        "Eddie Murphy",
        "Chris Rock",
        "Kevin Hart",
        "Dave Chappelle",
        "Ricky Gervais",
        "John Oliver",
        "Trevor Noah",
        "Jimmy Fallon",
        "Conan O'Brien",
        "Stephen Colbert",
        "James Corden",
        "Gordon Ramsay",
        "Jamie Oliver",
        "Anthony Bourdain",
        "David Attenborough",
        "Jack Ma",
        "Warren Buffett",
        "Bernard Arnault",
        "LeBron James",
        "Serena Williams",
        "Rafael Nadal",
        "Roger Federer",
        "Novak Djokovic",
        "Simone Biles",
        "Usain Bolt",
        "Michael Phelps",
        "Tiger Woods",
        "Kobe Bryant"
    ],
    "🐘 Zvieratá": [
        "Slon",
        "Žirafa",
        "Tučniak",
        "Krokodíl",
        "Medveď",
        "Lev",
        "Tiger",
        "Gorila",
        "Delfín",
        "Morský koník",
        "Pštros",
        "Flamingo",
        "Koala",
        "Lenivec",
        "Gepard",
        "Hroch",
        "Nosorožec",
        "Vlk",
        "Líška",
        "Zajac",
        "Panda",
        "Orangutan",
        "Kapibara",
        "Mravenečník",
        "Jaguár",
        "Orka",
        "Žralok",
        "Chobotnica",
        "Medúza",
        "Morský lev",
        "Sokol",
        "Páv",
        "Tukan",
        "Kolibrík",
        "Ara",
        "Komodo varan",
        "Iguana",
        "Axolotl",
        "Tardigrada",
        "Platypus",
        "Šimpanz",
        "Bonobo",
        "Gibón",
        "Lemur",
        "Tapír",
        "Okapi",
        "Serval",
        "Ocelot",
        "Puma",
        "Leguán",
        "Kameleon",
        "Gekón",
        "Hroznýš",
        "Kobra",
        "Mamba",
        "Pytón",
        "Vakovlk",
        "Kengura",
        "Vombat",
        "Ježura",
        "Narvál",
        "Beluga",
        "Manatee",
        "Dugong",
        "Tuleň",
        "Mrož",
        "Vydra",
        "Bobor",
        "Skunks",
        "Dikobraz",
        "Armadilo",
        "Jazvec",
        "Tchor",
        "Lasica",
        "Hranostaj",
        "Kuna",
        "Ondatra",
        "Nutria",
        "Svišť",
        "Syseľ",
        "Plch",
        "Jarac",
        "Bison",
        "Gnu",
        "Impala",
        "Springbok",
        "Kudu",
        "Oryx",
        "Addax",
        "Eland",
        "Zebra",
        "Quagga",
        "Lama",
        "Vikuňa",
        "Alpaka",
        "Guanako",
        "Ťava",
        "Dromedár",
        "Yak",
        "Sob",
        "Los",
        "Jeleň",
        "Srnec",
        "Kamzík",
        "Muflón",
        "Zubor",
        "Medveď hnedý",
        "Medveď polárny",
        "Panda červená",
        "Mangusta",
        "Hyena",
        "Šakal",
        "Divoký pes",
        "Dingo",
        "Kojot",
        "Líška arktická",
        "Vlk arktický",
        "Tuleň leopardí",
        "Tučniak cisársky",
        "Albatros",
        "Kondor",
        "Sup",
        "Orol",
        "Jastrab",
        "Sokol sťahovavý",
        "Výr",
        "Sova snežná",
        "Papagáj",
        "Kakadu",
        "Lori",
        "Pelikán",
        "Čajka",
        "Kormorán",
        "Volavka",
        "Bocian",
        "Žeriav",
        "Čáp",
        "Lastovička",
        "Rondón",
        "Kolibřík",
        "Rajka",
        "Lyrebird",
        "Kasuár",
        "Kivi",
        "Emu",
        "Piranha",
        "Úhor elektrický",
        "Latimeria",
        "Murena",
        "Manta",
        "Pila",
        "Kladivohlavý žralok",
        "Beluga jeseter"
    ],
    "🍕 Jedlo": [
        "Pizza",
        "Sushi",
        "Burger",
        "Tacos",
        "Špagety",
        "Croissant",
        "Palačinky",
        "Zmrzlina",
        "Čokoláda",
        "Bagel",
        "Ramen",
        "Hummus",
        "Guacamole",
        "Tiramisu",
        "Fondue",
        "Paella",
        "Gyros",
        "Rizoto",
        "Lasagne",
        "Waffle",
        "Dim sum",
        "Pho",
        "Bibimbap",
        "Shawarma",
        "Falafel",
        "Nachos",
        "Bruschetta",
        "Ceviche",
        "Moussaka",
        "Pierogi",
        "Bryndzové halušky",
        "Langoše",
        "Trdelník",
        "Kürtőskalács",
        "Macaron",
        "Churros",
        "Baklava",
        "Mochi",
        "Poke bowl",
        "Pad Thai",
        "Tom Yum",
        "Green curry",
        "Massaman curry",
        "Nasi goreng",
        "Rendang",
        "Satay",
        "Laksa",
        "Bao bun",
        "Peking duck",
        "Kung pao",
        "Mapo tofu",
        "Hot pot",
        "Dumplings",
        "Spring roll",
        "Bánh mì",
        "Gỏi cuốn",
        "Biryani",
        "Butter chicken",
        "Tikka masala",
        "Dal",
        "Naan",
        "Samosa",
        "Chutney",
        "Raita",
        "Lassi",
        "Shakshuka",
        "Tagine",
        "Couscous",
        "Harissa",
        "Ful medames",
        "Injera",
        "Jollof rice",
        "Suya",
        "Piri piri",
        "Borscht",
        "Goulash",
        "Schnitzel",
        "Knedľa",
        "Svíčková",
        "Flammkuchen",
        "Bratwurst",
        "Pretzel",
        "Sauerkraut",
        "Stroganoff",
        "Blini",
        "Caviar",
        "Pelmeni",
        "Okroshka",
        "Pastrami",
        "Reuben sandwich",
        "Clam chowder",
        "Lobster roll",
        "BBQ ribs",
        "Pulled pork",
        "Coleslaw",
        "Cornbread",
        "Pancakes",
        "French toast",
        "Eggs Benedict",
        "Granola",
        "Açaí bowl",
        "Smoothie bowl",
        "Avocado toast",
        "Crème brûlée",
        "Soufflé",
        "Profiterole",
        "Éclair",
        "Tarte Tatin",
        "Galette",
        "Quiche",
        "Ratatouille",
        "Bouillabaisse",
        "Cassoulet",
        "Coq au vin",
        "Beef bourguignon",
        "Osso buco",
        "Carpaccio",
        "Prosciutto",
        "Panna cotta",
        "Gelato",
        "Cannoli",
        "Biscotti",
        "Panettone",
        "Focaccia",
        "Ciabatta",
        "Burrata",
        "Caprese",
        "Antipasto",
        "Cevapi",
        "Burek",
        "Ajvar",
        "Rakija",
        "Kimchi",
        "Bulgogi",
        "Japchae",
        "Tteokbokki",
        "Sundubu jjigae",
        "Tempura",
        "Yakitori",
        "Udon",
        "Soba",
        "Takoyaki",
        "Onigiri",
        "Edamame",
        "Miso polievka",
        "Gyoza",
        "Empanada",
        "Arepa",
        "Chimichurri",
        "Dulce de leche",
        "Brigadeiro",
        "Caipirinha",
        "Horchata",
        "Agua fresca"
    ],
    "🏆 Šport": [
        "Futbal",
        "Tenis",
        "Basketbal",
        "Plávanie",
        "Atletika",
        "Cyklistika",
        "Lyžovanie",
        "Box",
        "Volejbal",
        "Golf",
        "Rugby",
        "Kriket",
        "Surfovanie",
        "Snowboard",
        "Vzpieranie",
        "Karate",
        "Judo",
        "Biatlon",
        "Skoky na lyžiach",
        "Stolný tenis",
        "Šerm",
        "Lukostrelba",
        "Triatlon",
        "Moderná gymnastika",
        "Skoky do vody",
        "Sánkovanie",
        "Curling",
        "Plachtenie",
        "Americký futbal",
        "Baseball",
        "Lacrosse",
        "Polo",
        "Ľadový hokej",
        "Inline korčuľovanie",
        "Skateboard",
        "Parkour",
        "Horolezectvo",
        "Padák",
        "Wingsuit",
        "Freediving",
        "Badminton",
        "Squash",
        "Raketbal",
        "Hádzaná",
        "Pólista",
        "Vodné pólo",
        "Synchronizované plávanie",
        "Veslovanie",
        "Kajak",
        "Kanoe",
        "Windsurfing",
        "Kitesurfing",
        "Wakeboard",
        "Motocross",
        "Rallye",
        "Formule 1",
        "MotoGP",
        "NASCAR",
        "Bobsled",
        "Skeleton",
        "Krasokorčuľovanie",
        "Rýchlokorčuľovanie",
        "Alpské lyžovanie",
        "Bežecké lyžovanie",
        "Freestyle lyžovanie",
        "Skialpinizmus",
        "Skicross",
        "Snowboardcross",
        "Halfpipe",
        "Big air",
        "Plážový volejbal",
        "Plážový futbal",
        "Futsal",
        "Florbal",
        "Hokejbal",
        "Ringuette",
        "Bandy",
        "Softball",
        "Rounders",
        "Pétanque",
        "Bocce",
        "Kuželky",
        "Bowling",
        "Biliard",
        "Šach",
        "Šachovnica",
        "Dáma",
        "Go",
        "Mahjong",
        "eSports",
        "Counter-Strike",
        "League of Legends",
        "Dota 2",
        "Fortnite",
        "FIFA",
        "NBA 2K",
        "Rocket League",
        "MMA",
        "Zápasenie",
        "Kickbox",
        "Muay Thai",
        "Brazílske jiu-jitsu",
        "Aikido",
        "Taekwondo",
        "Kung fu",
        "Capoeira",
        "Gymnastika",
        "Akrobacia",
        "Trampolín",
        "Pentatlon",
        "Dekatlon",
        "Maratón",
        "Ultramaratón",
        "Ironman",
        "Spartan Race",
        "OCR",
        "CrossFit",
        "Silový trojboj",
        "Kulturistika",
        "Fitness",
        "Jachting",
        "Veslárstvo",
        "Dračie lode",
        "Stand-up paddling",
        "Lanový park",
        "Via ferrata",
        "Bouldering",
        "Skalolezenie",
        "Paragliding",
        "Paraglidingové závody",
        "BASE jumping",
        "Spearfishing",
        "Podvodné rugby",
        "Orientálny beh",
        "Rogaining",
        "Adventure racing"
    ],
    "🇸🇰 Slovensko": [
        "Tatry",
        "Bratislava",
        "Košice",
        "Bryndzové halušky",
        "Čičmany",
        "Vlkolínec",
        "Bojnice",
        "Devín",
        "Jánošík",
        "Orava",
        "Východná",
        "Demänovka",
        "Kriváň",
        "Dunaj",
        "Váh",
        "Spišský hrad",
        "Liptov",
        "Záhorie",
        "Šariš",
        "Tokaj",
        "Banská Bystrica",
        "Žilina",
        "Prešov",
        "Nitra",
        "Trnava",
        "Trenčín",
        "Poprad",
        "Bardejov",
        "Levoča",
        "Kežmarok",
        "Dobšinská ľadová jaskyňa",
        "Slovenský raj",
        "Muránska planina",
        "Babia hora",
        "Gerlachovský štít",
        "Slavín",
        "Michal Šimečka",
        "Milan Rastislav Štefánik",
        "Ľudovít Štúr",
        "Alexander Dubček",
        "Devin Castle",
        "Červený Kameň",
        "Beckov",
        "Strečno",
        "Lietava",
        "Hrad Krásna Hôrka",
        "Zvolen",
        "Fiľakovo",
        "Muráň",
        "Tatranská Lomnica",
        "Štrbské Pleso",
        "Chopok",
        "Dumbier",
        "Poľana",
        "Vtáčnik",
        "Malá Fatra",
        "Veľká Fatra",
        "Záhorská nížina",
        "Podunajská nížina",
        "Východoslovenská nížina",
        "Hornád",
        "Hron",
        "Morava",
        "Laborec",
        "Ružomberok",
        "Martin",
        "Piešťany",
        "Senec",
        "Pezinok",
        "Modra",
        "Svätý Jur",
        "Stupava",
        "Malacky",
        "Senica",
        "Skalica",
        "Myjava",
        "Handlová",
        "Prievidza",
        "Partizánske",
        "Topoľčany",
        "Zlaté Moravce",
        "Levice",
        "Šahy",
        "Štúrovo",
        "Komárno",
        "Dunajská Streda",
        "Galanta",
        "Hlohovec",
        "Leopoldov",
        "Vrbové",
        "Dubnica",
        "Ilava",
        "Púchov",
        "Bytča",
        "Kysucké Nové Mesto",
        "Čadca",
        "Turčianske Teplice",
        "Dolný Kubín",
        "Námestovo",
        "Tvrdošín",
        "Liptovský Mikuláš",
        "Brezno",
        "Rimavská Sobota",
        "Rožňava",
        "Gelnica",
        "Spišská Nová Ves",
        "Spišská Belá",
        "Stará Ľubovňa",
        "Sabinov",
        "Vranov nad Topľou",
        "Humenné",
        "Snina",
        "Michalovce",
        "Sobrance",
        "Trebišov",
        "Veľký Krtíš",
        "Janko Kráľ",
        "Pavol Országh Hviezdoslav",
        "Martin Kukučín",
        "Božena Slančíková-Timrava",
        "Ivan Krasko",
        "Samo Chalupka",
        "Andrej Sládkovič",
        "Ján Kollár",
        "Štefan Moyses",
        "Anton Bernolák",
        "Juraj Fándly",
        "Matúš Čák Trenčiansky",
        "Svätopluk",
        "Rastislav",
        "Pribina",
        "Mojmír",
        "Veľká Morava",
        "Cyrila Metod",
        "Bratislavský hrad",
        "Slovenská filharmónia",
        "Slovenské národné divadlo",
        "SNM",
        "Comenius",
        "ESET",
        "Pixel Federation",
        "Zlatý Bažant",
        "Kofola",
        "Vinea",
        "Mattoni"
    ],
    "💻 IT & Technológie": [
        "Internet",
        "Umelá inteligencia",
        "Blockchain",
        "Cloud",
        "Cybersecurity",
        "Big Data",
        "Machine Learning",
        "Python",
        "JavaScript",
        "Linux",
        "GitHub",
        "Docker",
        "Kubernetes",
        "ChatGPT",
        "Tesla",
        "SpaceX",
        "iPhone",
        "Android",
        "Wi-Fi",
        "Bluetooth",
        "USB",
        "Procesor",
        "GPU",
        "Serverová farma",
        "Firewall",
        "VPN",
        "API",
        "Database",
        "Open source",
        "Startup",
        "Silicon Valley",
        "App Store",
        "Streamlit",
        "TensorFlow",
        "React",
        "TypeScript",
        "Agile",
        "Scrum",
        "DevOps",
        "Metaverse",
        "NFT",
        "Kvantový počítač",
        "Deep Learning",
        "Neural Network",
        "Computer Vision",
        "NLP",
        "Reinforcement Learning",
        "GPT-4",
        "Claude",
        "Gemini",
        "Llama",
        "Stable Diffusion",
        "DALL-E",
        "Midjourney",
        "Sora",
        "Raspberry Pi",
        "Arduino",
        "ESP32",
        "FPGA",
        "ASIC",
        "ARM",
        "RISC-V",
        "x86",
        "Apple Silicon",
        "M1",
        "SSD",
        "NVMe",
        "RAM",
        "ROM",
        "Cache",
        "TCP/IP",
        "HTTP",
        "HTTPS",
        "DNS",
        "CDN",
        "REST API",
        "GraphQL",
        "WebSocket",
        "gRPC",
        "OAuth",
        "JWT",
        "SSH",
        "SSL",
        "TLS",
        "Encryption",
        "SQL",
        "NoSQL",
        "MongoDB",
        "PostgreSQL",
        "Redis",
        "Elasticsearch",
        "Kafka",
        "RabbitMQ",
        "Hadoop",
        "Spark",
        "AWS",
        "Azure",
        "Google Cloud",
        "Heroku",
        "Vercel",
        "Terraform",
        "Ansible",
        "Jenkins",
        "CI/CD",
        "Git",
        "Linux kernel",
        "Ubuntu",
        "Debian",
        "Arch Linux",
        "MacOS",
        "Windows",
        "iOS",
        "Flutter",
        "React Native",
        "Swift",
        "Kotlin",
        "Java",
        "C++",
        "Rust",
        "Go",
        "Ruby",
        "PHP",
        "Scala",
        "R",
        "Jupyter",
        "VS Code",
        "IntelliJ",
        "Vim",
        "Emacs",
        "Stack Overflow",
        "npm",
        "pip",
        "Homebrew",
        "Microservices",
        "Serverless",
        "Edge computing",
        "IoT",
        "Smart home",
        "Wearables",
        "AR",
        "VR",
        "Oculus",
        "HoloLens",
        "Apple Vision Pro",
        "Waymo",
        "Autopilot",
        "LiDAR",
        "Self-driving",
        "Starlink",
        "5G",
        "6G",
        "Satellite internet",
        "Bitcoin",
        "Ethereum",
        "Smart contract",
        "DeFi",
        "Web3",
        "Phishing",
        "Ransomware",
        "Zero-day",
        "Penetration testing",
        "Bug bounty",
        "White hat",
        "Dark web",
        "Tor",
        "Moore's law",
        "Turing test",
        "Singularity"
    ],
    "📜 História": [
        "Staroveký Rím",
        "Napoleón Bonaparte",
        "Kleopatra",
        "Vikingovia",
        "Stredovek",
        "Renesancia",
        "Druhá svetová vojna",
        "Studená vojna",
        "Francúzska revolúcia",
        "Americká revolúcia",
        "Kolumbovanie",
        "Veľká čínska múr",
        "Pyramídy",
        "Koloseum",
        "Trójska vojna",
        "Alexander Veľký",
        "Džingischán",
        "Atila",
        "Juliusz Cézar",
        "Mária Terézia",
        "Habsburgovci",
        "Osmanská ríša",
        "Aztékovia",
        "Inkovia",
        "Majovia",
        "Rímska ríša",
        "Byzantská ríša",
        "Zlatá horda",
        "Magna Carta",
        "Gutenbergova biblia",
        "Prvá svetová vojna",
        "Holokaust",
        "Berlínsky múr",
        "Apollo 11",
        "Hirošima",
        "Titanic",
        "Ruská revolúcia",
        "Egyptská ríša",
        "Mezopotámia",
        "Sumerovia",
        "Babylón",
        "Asýrska ríša",
        "Perzská ríša",
        "Grécka ríša",
        "Sparťania",
        "Macedónska ríša",
        "Kartágo",
        "Fenicia",
        "Minojská civilizácia",
        "Mycénska civilizácia",
        "Etruské kultúry",
        "Galovia",
        "Kelti",
        "Germánske kmene",
        "Hunovia",
        "Avari",
        "Frankská ríša",
        "Karol Veľký",
        "Svätá ríša rímska",
        "Križiacke výpravy",
        "Rytieri",
        "Feudalizmus",
        "Čierny mor",
        "Inkvizícia",
        "Reformácia",
        "Martin Luther",
        "Ján Kalvín",
        "Husitské hnutie",
        "Ján Hus",
        "Tridsaťročná vojna",
        "Vestfálsky mier",
        "Augsburský mier",
        "Slávna revolúcia",
        "Absolútna monarchia",
        "Ľudovít XIV.",
        "Osvietenstvo",
        "Encyklopédia",
        "Voltaire",
        "Rousseau",
        "Priemyselná revolúcia",
        "Parný stroj",
        "Baníctvo",
        "Kolonializmus",
        "Otrokárstvo",
        "Abolicionizmus",
        "Americká občianska vojna",
        "Abraham Lincoln",
        "Bismarck",
        "Zjednotenie Nemecka",
        "Zjednotenie Talianska",
        "Prvá republika",
        "Druhá republika",
        "Weimarska republika",
        "Fašizmus",
        "Mussolini",
        "Hitler",
        "Stalin",
        "Churchill",
        "Roosevelt",
        "De Gaulle",
        "Norimberský proces",
        "Mierová zmluva",
        "OSN",
        "Dekolonizácia",
        "Kórejská vojna",
        "Vietnamská vojna",
        "Kubánska kríza",
        "Berlínska kríza",
        "Preteky v zbrojení",
        "Vesmírne preteky",
        "Sputnik",
        "Perestrojka",
        "Glasnosť",
        "Gorbačov",
        "Jeltsin",
        "Rozpad ZSSR",
        "Pád železnej opony",
        "Nežná revolúcia",
        "Znovuzjednotenie Nemecka",
        "Juhoslovanské vojny",
        "Rwandská genocída",
        "Apartheid",
        "Nelson Mandela",
        "Čínska kultúrna revolúcia",
        "Mao Ce-tung",
        "Japonské impérium"
    ],
    "🗺️ Geografia": [
        "Amazon",
        "Sahara",
        "Everest",
        "Mariana priekopa",
        "Nílska delta",
        "Antarktída",
        "Arktída",
        "Sibirská tajga",
        "Grand Canyon",
        "Victoria Falls",
        "Mŕtve more",
        "Bajkalské jazero",
        "Himaláje",
        "Alpy",
        "Kordillery",
        "Ural",
        "Kaukaz",
        "Mississippi",
        "Volga",
        "Níl",
        "Kongo",
        "Mekong",
        "Tichý oceán",
        "Atlantický oceán",
        "Indický oceán",
        "Stredozemné more",
        "Červené more",
        "Arabské more",
        "Amazónsky prales",
        "Savana",
        "Tundra",
        "Step",
        "Coral reef",
        "Gejzír",
        "Sopka",
        "Tsunami",
        "Tornádo",
        "Polárna žiara",
        "Monsún",
        "El Niño",
        "Pangea",
        "Tektonické dosky",
        "Zemetrasenie",
        "Magma",
        "Lávový prúd",
        "Vulkanický ostrov",
        "Atol",
        "Fjord",
        "Delta",
        "Ústie rieky",
        "Jazero",
        "Mokraď",
        "Mangrov",
        "Koral",
        "Bioregión",
        "Ekosystém",
        "Biodiverzita",
        "Tropický dažďový les",
        "Subtropický les",
        "Boreálny les",
        "Pampa",
        "Préria",
        "Púšť Gobi",
        "Atacama",
        "Namib",
        "Kalahari",
        "Patagónia",
        "Tibetská plošina",
        "Dekanská plošina",
        "Arabský polostrov",
        "Pyreneje",
        "Karpaty",
        "Balkán",
        "Škandinávia",
        "Britské ostrovy",
        "Stredozemie",
        "Blízky východ",
        "Ďaleký východ",
        "Juhovýchodná Ázia",
        "Stredná Ázia",
        "Sibír",
        "Severná Amerika",
        "Stredná Amerika",
        "Karibik",
        "Južná Amerika",
        "Subsaharská Afrika",
        "Severná Afrika",
        "Roh Afriky",
        "Južná Afrika",
        "Oceánia",
        "Melanézia",
        "Mikronézia",
        "Polynézia",
        "Maori",
        "Aborigéni",
        "Ľadovec",
        "Ľadovcový ústup",
        "Klimatická zmena",
        "Skleníkový efekt",
        "Ozónová diera",
        "Kyslý dážď",
        "Príliv",
        "Odliv",
        "Morský prúd",
        "Golfský prúd",
        "Humboldt prúd",
        "Kuroshio",
        "ENSO",
        "La Niña",
        "Tajfún",
        "Hurikán",
        "Cyklón",
        "Búrka",
        "Blizzard",
        "Sucho",
        "Povodeň",
        "Zosuv pôdy",
        "Kaňon",
        "Skalné útvary",
        "Stalaktit",
        "Stalagmit",
        "Jaskynný systém",
        "Podzemná rieka",
        "Artézska studňa",
        "Geotermálna energia",
        "Prírodný rezervát",
        "Národný park",
        "UNESCO",
        "Svetové dedičstvo",
        "Biosférická rezervácia"
    ],
    "🏙️ Hlavné mestá": [
        "Paríž",
        "Londýn",
        "Berlín",
        "Madrid",
        "Rím",
        "Atény",
        "Viedeň",
        "Praha",
        "Varšava",
        "Budapešť",
        "Brusel",
        "Amsterdam",
        "Štokholm",
        "Oslo",
        "Kodaň",
        "Helsinki",
        "Lisabon",
        "Dublin",
        "Záhreb",
        "Bukurešť",
        "Sofía",
        "Belehrad",
        "Kyjev",
        "Moskva",
        "Minsk",
        "Washington D.C.",
        "Ottawa",
        "Mexico City",
        "Buenos Aires",
        "Brasília",
        "Tokio",
        "Peking",
        "Soul",
        "Bangkok",
        "Jakarta",
        "Nairobi",
        "Káhira",
        "Pretória",
        "Abuja",
        "Addis Abeba",
        "Canberra",
        "Wellington",
        "Lima",
        "Bogotá",
        "Santiago",
        "Bratislava",
        "Ľubľana",
        "Sarajevo",
        "Skopje",
        "Podgorica",
        "Tirana",
        "Nikózia",
        "Valletta",
        "Reykjavík",
        "Andorra la Vella",
        "Vaduz",
        "San Marino",
        "Vatikán",
        "Monaco",
        "Luxemburg",
        "Bern",
        "Vilnius",
        "Riga",
        "Tallinn",
        "Chisinau",
        "Tbilisi",
        "Jerevan",
        "Baku",
        "Nur-Sultan",
        "Taškent",
        "Bištek",
        "Dušanbe",
        "Ašchabad",
        "Kábul",
        "Islamabad",
        "Naypyidaw",
        "Vientiane",
        "Phnom Penh",
        "Kuala Lumpur",
        "Manila",
        "Singapur",
        "Bandar Seri Begawan",
        "Dili",
        "Port Moresby",
        "Suva",
        "Honiara",
        "Port Vila",
        "Nuku'alofa",
        "Apia",
        "Funafuti",
        "Tarawa",
        "Majuro",
        "Palikir",
        "Koror",
        "Yaren",
        "Ngerulmud",
        "Abú Zabí",
        "Rijád",
        "Dauha",
        "Manáma",
        "Kuvajt",
        "Ammán",
        "Bejrút",
        "Damask",
        "Bagdad",
        "Teherán",
        "Ankara",
        "Jeruzalem",
        "Tel Aviv",
        "Muskat",
        "Sanaa",
        "Mogadišo",
        "Džibuti",
        "Asmara",
        "Chartúm",
        "Džuba",
        "Kampala",
        "Kigali",
        "Bujumbura",
        "Dar es Salaam",
        "Lusaka",
        "Harare",
        "Maputo",
        "Antananarivo",
        "Port Louis",
        "Moroni",
        "Victoria",
        "São Tomé",
        "Malabo",
        "Libreville",
        "Jaunde",
        "Bangui",
        "Brazzaville",
        "Kinshasa",
        "Luanda",
        "Windhoek",
        "Gaborone",
        "Maseru",
        "Mbabane",
        "Lomé",
        "Accra",
        "Abidžan",
        "Ouagadougou",
        "Bamako",
        "Niamej",
        "Ndjamena",
        "Yaoundé",
        "Conakry",
        "Freetown",
        "Monrovia",
        "Bissau",
        "Banjul",
        "Dakar",
        "Rabat",
        "Tunis",
        "Tripolis",
        "Algier",
        "Quito",
        "Caracas",
        "Georgetown",
        "Paramaribo",
        "Cayenne",
        "La Paz",
        "Asunción",
        "Montevideo"
    ],
    "🔬 Veda & Príroda": [
        "Gravitácia",
        "Evolúcia",
        "DNA",
        "Fotosyntéza",
        "Osmóza",
        "Periodická tabuľka",
        "Atóm",
        "Čierna diera",
        "Supernova",
        "Fotoelektrický jav",
        "Relativita",
        "Kvantová fyzika",
        "Termodinámika",
        "Elektromagnetizmus",
        "Jadrová fúzia",
        "Klonování",
        "CRISPR",
        "Vakcína",
        "Antibiotiká",
        "Penicilín",
        "Gravitačné vlny",
        "Temná hmota",
        "Multiverse",
        "Wormhole",
        "Schrödingerova mačka",
        "Heisenbergov princíp",
        "Darwinova teória",
        "Mendelove zákony",
        "Newtonove zákony",
        "Archimédov zákon",
        "Pythagorova veta",
        "Eulerovo číslo",
        "Fibonacciho postupnosť",
        "Chaos theory",
        "Fraktál",
        "Veľký tresk",
        "Tmavá energia",
        "Neutrónovská hviezda",
        "Pulzar",
        "Kvásar",
        "Galaxia",
        "Mliečna dráha",
        "Andromeda",
        "Hubbleov teleskop",
        "Jamesov vesmírny teleskop",
        "Marsová misia",
        "Voyager",
        "Pioneer",
        "New Horizons",
        "ISS",
        "Kozmická loď",
        "Satelit",
        "Kozmický odpad",
        "Protón",
        "Neutróm",
        "Elektrón",
        "Kvark",
        "Bozon Higgs",
        "Antimatter",
        "Plazma",
        "Fúzia",
        "Fisia",
        "Rádioaktivita",
        "Röntgen",
        "Gama žiarenie",
        "UV žiarenie",
        "Infračervené žiarenie",
        "Svetelná rýchlosť",
        "Časová dilataácia",
        "Červený posun",
        "Dopplerov efekt",
        "Interferencia",
        "Difrakcia",
        "Polarizácia",
        "Optika",
        "Holografia",
        "Laser",
        "LED",
        "Fotovoltaika",
        "Supravodivosť",
        "Nanotech",
        "Graphene",
        "Fullerén",
        "Proteín",
        "Enzým",
        "Hormón",
        "Receptor",
        "Synaps",
        "Neurón",
        "Mozgová kôra",
        "Hipokampus",
        "Amygdala",
        "Serotonín",
        "Dopamín",
        "Oxytocín",
        "Kortizol",
        "Imunitný systém",
        "Lymfatický systém",
        "Mikrobióm",
        "Vírus",
        "Baktéria",
        "Huba",
        "Prión",
        "Parazit",
        "Ekológia",
        "Potravinový reťazec",
        "Symbioza",
        "Parazitizmus",
        "Klimax",
        "Sukcesia",
        "Biodiverzita",
        "Masové vyhynutie",
        "Fosilný záznam",
        "Stratigrafie",
        "Geologická éra",
        "Kambrium",
        "Jurská perióda",
        "Krieda",
        "Paleogén",
        "Dinosaurus",
        "Mammut",
        "Sabľozubý tiger",
        "Neandertalec",
        "Homo sapiens",
        "Antropocén",
        "Permafrost",
        "Ľadová doba"
    ],
    "🎵 Hudba": [
        "Beatles",
        "Rolling Stones",
        "Queen",
        "ABBA",
        "Michael Jackson",
        "Elvis Presley",
        "Bob Dylan",
        "Jimi Hendrix",
        "Led Zeppelin",
        "Pink Floyd",
        "Nirvana",
        "U2",
        "Coldplay",
        "Radiohead",
        "Daft Punk",
        "Madonna",
        "Whitney Houston",
        "Mariah Carey",
        "Frank Sinatra",
        "Louis Armstrong",
        "Miles Davis",
        "Bob Marley",
        "Mozart",
        "Beethoven",
        "Bach",
        "Chopin",
        "Vivaldi",
        "Gitara",
        "Husle",
        "Klavír",
        "Bubnová súprava",
        "Saxofón",
        "Hip-hop",
        "Jazz",
        "Klasická hudba",
        "Reggae",
        "Techno",
        "Grammy",
        "Woodstock",
        "Eurovision",
        "Coachella",
        "Fleetwood Mac",
        "Eagles",
        "AC/DC",
        "Metallica",
        "Iron Maiden",
        "Black Sabbath",
        "Ozzy Osbourne",
        "Guns N' Roses",
        "Bon Jovi",
        "Aerosmith",
        "Red Hot Chili Peppers",
        "Foo Fighters",
        "Pearl Jam",
        "Soundgarden",
        "Alice in Chains",
        "Stone Temple Pilots",
        "The Cure",
        "Depeche Mode",
        "New Order",
        "Joy Division",
        "The Smiths",
        "Morrissey",
        "Oasis",
        "Blur",
        "Pulp",
        "Arctic Monkeys",
        "The Strokes",
        "The White Stripes",
        "Arcade Fire",
        "Vampire Weekend",
        "Tame Impala",
        "David Bowie",
        "Elton John",
        "Prince",
        "Freddie Mercury",
        "Mick Jagger",
        "Keith Richards",
        "Bruce Springsteen",
        "Stevie Wonder",
        "Ray Charles",
        "Aretha Franklin",
        "James Brown",
        "Otis Redding",
        "Sam Cooke",
        "Al Green",
        "Marvin Gaye",
        "Smokey Robinson",
        "Diana Ross",
        "Tina Turner",
        "Donna Summer",
        "Gloria Gaynor",
        "Bee Gees",
        "Earth Wind Fire",
        "Flute",
        "Trúbka",
        "Trombon",
        "Klarinet",
        "Hoboj",
        "Harfa",
        "Cello",
        "Kontrabas",
        "Mandolína",
        "Banjo",
        "Ukulele",
        "Baskytara",
        "Syntetizátor",
        "Organ",
        "Akordeon",
        "Pop",
        "Rock",
        "Metal",
        "Punk",
        "Indie",
        "R&B",
        "Soul",
        "Funk",
        "Disco",
        "Electronic",
        "House",
        "Trance",
        "Drum and bass",
        "Dubstep",
        "Trap",
        "Country",
        "Folk",
        "Blues",
        "Gospel",
        "Spiritual",
        "Opera",
        "Musical",
        "Symfonická hudba",
        "Komorná hudba",
        "Filharmónia",
        "Dirigent",
        "Orchester",
        "Zbor",
        "A capella",
        "Vinyl",
        "Walkman",
        "iPod",
        "Spotify",
        "Apple Music",
        "MTV",
        "VH1",
        "Top of the Pops",
        "American Idol",
        "X Factor",
        "Glastonbury",
        "Lollapalooza",
        "Reading Festival",
        "Tomorrowland"
    ],
    "⚽ Futbalové fakty": [
        "Pelé",
        "Maradona",
        "Ronaldo",
        "Messi",
        "Zidane",
        "Ronaldinho",
        "Beckham",
        "Platini",
        "Cruyff",
        "Puskas",
        "FC Barcelona",
        "Real Madrid",
        "Manchester United",
        "Bayern Mníchov",
        "Juventus",
        "Liverpool",
        "Chelsea",
        "PSG",
        "AC Miláno",
        "Inter Miláno",
        "FIFA World Cup",
        "UEFA Champions League",
        "El Clásico",
        "Derby della Madonnina",
        "Zlatá lopta",
        "Hat-trick",
        "Offside",
        "Penalta",
        "Červená karta",
        "Wembley",
        "Maracanã",
        "Camp Nou",
        "San Siro",
        "Anfield",
        "Brazília 5x majster sveta",
        "Nemecko 4x majster sveta",
        "Najdrahší hráč Neymar",
        "Prvé MS 1930 Uruguay",
        "Goal of the century Maradona",
        "Hand of God",
        "Gól za 11 sekúnd",
        "Najvyššia prehra 31:0 Samoa",
        "Hráč bez nôh Marcelo",
        "VAR technológia",
        "Goal-line technológia",
        "Zlatá kopačka",
        "Treble",
        "Najrýchlejší gól 2 sekundy",
        "Ronaldo 900 gólov",
        "Messi 8x Zlatá lopta",
        "Kylian Mbappé",
        "Erling Haaland",
        "Vinicius Jr",
        "Pedri",
        "Bellingham",
        "Lamine Yamal",
        "Bukayo Saka",
        "Phil Foden",
        "Marcus Rashford",
        "Mo Salah",
        "Sadio Mané",
        "Roberto Firmino",
        "Virgil van Dijk",
        "Alisson Becker",
        "Ederson",
        "Manuel Neuer",
        "Gianluigi Buffon",
        "Iker Casillas",
        "Peter Schmeichel",
        "Oliver Kahn",
        "Roberto Carlos",
        "Cafu",
        "Paolo Maldini",
        "Franco Baresi",
        "Franz Beckenbauer",
        "Bobby Moore",
        "Fabio Cannavaro",
        "Ronaldo Nazário",
        "Rivaldo",
        "Romário",
        "Adriano",
        "Thierry Henry",
        "Patrick Vieira",
        "Didier Drogba",
        "Zlatan Ibrahimović",
        "Andrés Iniesta",
        "Xavi Hernández",
        "Sergio Busquets",
        "Luis Suárez",
        "Neymar",
        "Dani Alves",
        "Gareth Bale",
        "Luka Modrić",
        "Toni Kroos",
        "Sergio Ramos",
        "Karim Benzema",
        "Robert Lewandowski",
        "Thomas Müller",
        "Kevin De Bruyne",
        "Eden Hazard",
        "Romelu Lukaku",
        "Antoine Griezmann",
        "Paul Pogba",
        "N'Golo Kanté",
        "Mesut Özil",
        "Miroslav Klose",
        "Gerd Müller",
        "Johan Cruyff",
        "Marco van Basten",
        "Ruud Gullit",
        "Paolo Rossi",
        "Roberto Baggio",
        "Alessandro Del Piero",
        "Francesco Totti",
        "Andrea Pirlo",
        "Gianluigi Donnarumma",
        "Bernabeu",
        "Allianz Arena",
        "Signal Iduna Park",
        "Old Trafford",
        "Emirates Stadium",
        "Etihad Stadium",
        "Stamford Bridge",
        "Parc des Princes",
        "Stade de France",
        "Azteca",
        "Copa América",
        "EURO",
        "Africa Cup of Nations",
        "Copa Libertadores",
        "Premier League",
        "La Liga",
        "Serie A",
        "Bundesliga",
        "Ligue 1"
    ],
    "🌍 Európa — geografia": [
        "Alpy",
        "Pyreneje",
        "Karpaty",
        "Balkán",
        "Škandinávia",
        "Britské ostrovy",
        "Iberský polostrov",
        "Apeninský polostrov",
        "Balkánsky polostrov",
        "Škandinávsky polostrov",
        "Stredozemné more",
        "Severné more",
        "Baltské more",
        "Čierne more",
        "Jadranské more",
        "Egejské more",
        "Tyrhénske more",
        "Jónske more",
        "Biskajský záliv",
        "Lamanšský prieliv",
        "Gibraltársky prieliv",
        "Bospor",
        "Dardanely",
        "Kerčský prieliv",
        "Skagerrak",
        "Kattegat",
        "Rýn",
        "Dunaj",
        "Volga",
        "Dneper",
        "Labe",
        "Odra",
        "Visla",
        "Temža",
        "Seine",
        "Loire",
        "Rhône",
        "Po",
        "Tibera",
        "Ebro",
        "Tagus",
        "Island",
        "Írsko",
        "Veľká Británia",
        "Korzika",
        "Sardínia",
        "Sicília",
        "Kréta",
        "Kypr",
        "Malta",
        "Baleárske ostrovy",
        "Kanárske ostrovy",
        "Azory",
        "Madeira",
        "Fínsko",
        "Nórsko",
        "Švédsko",
        "Dánsko",
        "Estónsko",
        "Lotyšsko",
        "Litva",
        "Poľsko",
        "Česko",
        "Slovensko",
        "Maďarsko",
        "Rakúsko",
        "Švajčiarsko",
        "Lichtenštajnsko",
        "Luxemburg",
        "Belgicko",
        "Holandsko",
        "Nemecko",
        "Francúzsko",
        "Španielsko",
        "Portugalsko",
        "Taliansko",
        "Grécko",
        "Albánsko",
        "Severné Macedónsko",
        "Kosovo",
        "Srbsko",
        "Čierna Hora",
        "Bosna a Hercegovina",
        "Chorvátsko",
        "Slovinsko",
        "Rumunsko",
        "Bulharsko",
        "Moldavsko",
        "Bielorusko",
        "Ukrajina",
        "Rusko",
        "Turecko",
        "Gruzínsko",
        "Arménsko",
        "Azerbajdžan",
        "Andorra",
        "Monaco",
        "San Marino",
        "Vatikán",
        "Monako",
        "Mont Blanc",
        "Matterhorn",
        "Grossglockner",
        "Olymp",
        "Vezuv",
        "Etna",
        "Stromboli",
        "Santorini",
        "Fjordy",
        "Tundra škandinávska",
        "Čierne lesy",
        "Pád",
        "Toskánsko",
        "Provença",
        "Bretónsko",
        "Normandia",
        "Bavorsko",
        "Prusko",
        "Flandry",
        "Valónia",
        "Transylvánia",
        "Morava",
        "Čechy",
        "Sliezko",
        "Mazúrsko",
        "Krim",
        "Donbas",
        "Galícia",
        "Podkarpatsko",
        "Lapónsko",
        "Shetlandské ostrovy",
        "Orknejské ostrovy",
        "Hebridy",
        "Faerské ostrovy"
    ],
    "🌍 Afrika — geografia": [
        "Sahara",
        "Namib",
        "Kalahari",
        "Okavango",
        "Serengeti",
        "Masai Mara",
        "Kilimandžáro",
        "Mount Kenya",
        "Ruwenzori",
        "Atlas",
        "Dračie hory",
        "Ahaggar",
        "Tibesti",
        "Níl",
        "Kongo",
        "Niger",
        "Zambezi",
        "Limpopo",
        "Orange",
        "Senegal",
        "Volta",
        "Benue",
        "Šebele",
        "Viktóriino jazero",
        "Tanganika",
        "Malawi",
        "Turkana",
        "Chad",
        "Assal",
        "Mŕtve more Afriky",
        "Viktóriine vodopády",
        "Mosi-oa-Tunya",
        "Madagaskar",
        "Zanzibar",
        "Pemba",
        "Comory",
        "Mauritius",
        "Réunion",
        "Seychely",
        "Kapverdy",
        "São Tomé",
        "Príncipe",
        "Kanárske ostrovy",
        "Sokotra",
        "Sahel",
        "Savana",
        "Tropický prales",
        "Mangrov",
        "Roh Afriky",
        "Mys Dobrej nádeje",
        "Mys Horn",
        "Suezský prieplav",
        "Bab el-Mandeb",
        "Mozambický prieplav",
        "Guinejský záliv",
        "Aden",
        "Somálsky polostrov",
        "Egypt",
        "Líbya",
        "Tunisko",
        "Alžírsko",
        "Maroko",
        "Mauritánia",
        "Mali",
        "Čad",
        "Sudán",
        "Etiópia",
        "Eritrea",
        "Džibuti",
        "Somálsko",
        "Keňa",
        "Uganda",
        "Rwanda",
        "Burundi",
        "Tanzánia",
        "Mozambik",
        "Zimbabwe",
        "Zambia",
        "Juhoafrická republika",
        "Namíbia",
        "Botswana",
        "Lesotho",
        "Svazijsko",
        "Angola",
        "DRK",
        "Kamerun",
        "Nigéria",
        "Ghana",
        "Pobrežie Slonoviny",
        "Burkina Faso",
        "Guinea",
        "Sierra Leone",
        "Libéria",
        "Pyramídy",
        "Sfinga",
        "Luxor",
        "Karnak",
        "Abu Simbel",
        "Great Zimbabwe",
        "Lalibela",
        "Timbuktú",
        "Kartágo",
        "Kruger National Park",
        "Ngorongoro",
        "Amboseli",
        "Tsavo",
        "Goraly horské",
        "Lev",
        "Slon africký",
        "Nosorožec",
        "Hroch",
        "Žirafa",
        "Zebra",
        "Gnu",
        "Gepard",
        "Leopard",
        "Hyena",
        "Šakal",
        "Surikaty",
        "Babuín",
        "Šimpanz",
        "Gorila nížinná",
        "Krokodíl nílsky",
        "Flamingo",
        "Pelikán",
        "Orlosup",
        "Sekretár"
    ],
    "🌏 Ázia — geografia": [
        "Himaláje",
        "Karakorum",
        "Hindu Kush",
        "Pamír",
        "Ťan-šan",
        "Altaj",
        "Ural",
        "Kaukaz",
        "Zagros",
        "Elburz",
        "Everest",
        "K2",
        "Kangčendžönga",
        "Lhoce",
        "Makalu",
        "Gobi",
        "Taklamakan",
        "Thar",
        "Rub al-Chali",
        "Negev",
        "Síbír",
        "Tajga",
        "Tundra",
        "Step",
        "Monsún",
        "Jang-c'-ťiang",
        "Žltá rieka",
        "Mekong",
        "Irrawaddy",
        "Ganga",
        "Brahmaputra",
        "Indus",
        "Tigris",
        "Eufrat",
        "Ob",
        "Irtyš",
        "Jenisej",
        "Lena",
        "Amur",
        "Bajkalské jazero",
        "Kaspické more",
        "Aralské jazero",
        "Mŕtve more",
        "Galilejské jazero",
        "Van Lake",
        "Poyang",
        "Tichý oceán",
        "Indický oceán",
        "Arabské more",
        "Bengálsky záliv",
        "Juhočínske more",
        "Japonské more",
        "Žlté more",
        "Východočínske more",
        "Okhotské more",
        "Bering",
        "Hormuzský prieliv",
        "Malacký prieliv",
        "Sundský prieliv",
        "Lomboský prieliv",
        "Japonské ostrovy",
        "Filipíny",
        "Indonézia",
        "Borneo",
        "Sumatra",
        "Java",
        "Celebes",
        "Nová Guinea",
        "Srí Lanka",
        "Andamanské ostrovy",
        "Maledivy",
        "Lacadivské ostrovy",
        "Japonsko",
        "Čína",
        "India",
        "Pakistan",
        "Bangladéš",
        "Nepál",
        "Bhután",
        "Mjanmarsko",
        "Thajsko",
        "Vietnam",
        "Kambodža",
        "Laos",
        "Malajzia",
        "Singapur",
        "Brunej",
        "Taiwan",
        "Južná Kórea",
        "Severná Kórea",
        "Mongolsko",
        "Kazachstan",
        "Uzbekistan",
        "Turkménsko",
        "Kirgizsko",
        "Tadžikistan",
        "Afganistan",
        "Irán",
        "Irak",
        "Sýria",
        "Libanon",
        "Izrael",
        "Jordánsko",
        "Saudská Arábia",
        "Kuvajt",
        "Bahrajn",
        "Katar",
        "SAE",
        "Omán",
        "Jemen",
        "Tbilisi",
        "Baku",
        "Jerevan",
        "Astana",
        "Taškent",
        "Tokio",
        "Shanghai",
        "Peking",
        "Mumbai",
        "Dillí",
        "Hongkong",
        "Bangkok",
        "Džakarta",
        "Manila",
        "Fuji",
        "Bali",
        "Komodo",
        "Angkor Wat",
        "Taj Mahal",
        "Veľká čínska múr",
        "Forbidden City",
        "Terra Cotta"
    ],
    "🌊 Voda a oceány": [
        "Tichý oceán",
        "Atlantický oceán",
        "Indický oceán",
        "Arktický oceán",
        "Antarktický oceán",
        "Mariana priekopa",
        "Puerto Rico priekopa",
        "Java priekopa",
        "Stredozemné more",
        "Červené more",
        "Arabské more",
        "Čierne more",
        "Kaspické more",
        "Baltské more",
        "Severné more",
        "Nórske more",
        "Barentsovo more",
        "Beringovo more",
        "Okhotské more",
        "Japonské more",
        "Juhočínske more",
        "Koralové more",
        "Tasmánske more",
        "Karibské more",
        "Sargasové more",
        "Amendický záliv",
        "Bengálsky záliv",
        "Guinejský záliv",
        "Biskajský záliv",
        "Hudsonov záliv",
        "Mexický záliv",
        "Perzský záliv",
        "Adenský záliv",
        "Golfský prúd",
        "Humboldt prúd",
        "Kuroshio",
        "Benguelský prúd",
        "Agulhaský prúd",
        "Canársky prúd",
        "Labradorský prúd",
        "Antarktický cirkumpolárny prúd",
        "Príliv",
        "Odliv",
        "Slapové sily",
        "Mesačný vplyv",
        "Tsunami",
        "Seiche",
        "Rogue wave",
        "Koralový útes",
        "Veľká bariérová bariéra",
        "Atol",
        "Mangrový les",
        "Morská tráva",
        "Kelp les",
        "Hydrotermálny prameň",
        "Čierny komín",
        "Studená sapa",
        "Bioluminiscencia",
        "Morský sneh",
        "Termoklína",
        "Haloglina",
        "Pynoklína",
        "Plankton",
        "Fytoplankton",
        "Zooplankton",
        "Krill",
        "Veľryba",
        "Kašalot",
        "Narval",
        "Beluga",
        "Delfín",
        "Orka",
        "Dugong",
        "Manatee",
        "Morský lev",
        "Tuleň",
        "Chobotnica",
        "Sépie",
        "Kalmar",
        "Nautilus",
        "Žralok biely",
        "Žralok veľrybí",
        "Kladivohlavý žralok",
        "Manta",
        "Elektrický rej",
        "Murena",
        "Barrakuda",
        "Ryba mečiar",
        "Tuniakz",
        "Losos",
        "Treska",
        "Sleď",
        "Jeseter",
        "Morský koník",
        "Pipefish",
        "Ropucha morská",
        "Hviezda morská",
        "Ježovka",
        "Krab",
        "Homár",
        "Kreveta",
        "Lastúra",
        "Slimák morský",
        "Koráľ",
        "Sasanka",
        "Medúza",
        "Fyziologická adaptácia",
        "Echolokácia",
        "Hĺbka oceánu",
        "Epipelagická zóna",
        "Mezopelagická zóna",
        "Batypelagická zóna",
        "Abysálna zóna",
        "Hadálna zóna",
        "Slanosť",
        "pH oceánu",
        "Acidifikácia oceánov",
        "Plastové ostrovy",
        "Mikroplasty",
        "Ropná škvrna",
        "Znečistenie oceánov",
        "Prelov ryb",
        "Morské rezervácie",
        "Desalinácia",
        "Prílivové elektrárne",
        "Vlnová energia"
    ],
    "⚔️ Druhá svetová vojna — fakty": [
        "Adolf Hitler",
        "Winston Churchill",
        "Franklin Roosevelt",
        "Joseph Stalin",
        "Benito Mussolini",
        "Hirohito",
        "Charles de Gaulle",
        "Dwight Eisenhower",
        "Bernard Montgomery",
        "Erwin Rommel",
        "Georgi Žukov",
        "Heinz Guderian",
        "Heinrich Himmler",
        "Joseph Goebbels",
        "Hermann Göring",
        "Rudolf Hess",
        "Albert Speer",
        "Reinhard Heydrich",
        "Claus von Stauffenberg",
        "Anne Frank",
        "Oskar Schindler",
        "Nacistické Nemecko",
        "Tretia ríša",
        "Fašistické Taliansko",
        "Japonské impérium",
        "Osi",
        "Spojenci",
        "Poľská invázia 1939",
        "Blitzkrieg",
        "Phony War",
        "Bitka o Britániu",
        "Londýnsky blitz",
        "Operácia Barbarossa",
        "Operácia Overlord",
        "Deň D",
        "Bitka pri Kursku",
        "Bitka pri Stalingrade",
        "Obliehanie Leningradu",
        "Bitka v Ardénach",
        "Bitka pri El Alameine",
        "Bitka pri Midway",
        "Bitka v Pacifiku",
        "Guadalcanal",
        "Operácia Market Garden",
        "Operácia Sea Lion",
        "Bitka o Berlín",
        "Pád Berlína",
        "Pearl Harbor",
        "7. december 1941",
        "Hirošima",
        "Nagasaki",
        "Atómová bomba",
        "Enola Gay",
        "Manhattan Project",
        "Robert Oppenheimer",
        "Holokaust",
        "Výsledné riešenie",
        "Koncentračné tábory",
        "Auschwitz",
        "Treblinka",
        "Sobibor",
        "Majdanek",
        "Wannseeská konferencia",
        "Krištáľová noc",
        "Geto",
        "Varšavské geto",
        "Varšavské povstanie",
        "Slovenské národné povstanie",
        "Banskobystrické povstanie",
        "Partizáni",
        "Odboj",
        "Kolaborácia",
        "Dunkerque",
        "Evakuácia",
        "Loď Bismarck",
        "U-Boot",
        "Atlantická bitka",
        "Konvoje",
        "Lend-Lease",
        "Teheránska konferencia",
        "Jaltská konferencia",
        "Postupimská konferencia",
        "Norimberský proces",
        "Oslobodenie Paríža",
        "Oslobodenie táborov",
        "Víťazný deň v Európe 8.5.1945",
        "Víťazný deň v Pacifiku 2.9.1945",
        "Nacistická propaganda",
        "Zyklon B",
        "SS",
        "Gestapo",
        "Wehrmacht",
        "Luftwaffe",
        "Kriegsmarine",
        "Spitfire",
        "Hurricane",
        "Messerschmitt",
        "Focke-Wulf",
        "Tiger tank",
        "T-34",
        "Sherman tank",
        "Panther",
        "V-1",
        "V-2",
        "Enigma",
        "Ultra",
        "Alan Turing",
        "Bletchley Park",
        "Dešifrovanie",
        "Špionáž",
        "SOE",
        "Červený kríž",
        "Ženevská konvencia",
        "Vojnoví zajatci"
    ],
    "📺 Televízne postavy": [
    "Homer Simpson",
    "Walter White",
    "Michael Scott",
    "Sheldon Cooper",
    "Barney Stinson",
    "Eleven",
    "Wednesday Addams",
    "Rick Sanchez",
    "Morty Smith",
    "Daenerys Targaryen",
    "Jon Snow",
    "Sherlock Holmes",
    "Peaky Blinder Thomas Shelby",
    "Ted Lasso",
    "Dexter Morgan",
    "Saul Goodman",
    "House M.D.",
    "Rachel Green",
    "Joey Tribbiani",
    "Monica Geller"
],

"🌊 Morské stvorenia": [
    "Žralok",
    "Delfín",
    "Veľryba",
    "Orka",
    "Chobotnica",
    "Sépie",
    "Medúza",
    "Hviezdica",
    "Morský koník",
    "Manta",
    "Muréna",
    "Korál",
    "Krab",
    "Homár",
    "Kreveta",
    "Lastúra",
    "Morský lev",
    "Tuleň",
    "Narval",
    "Beluga"
],

"🏟️ Športové tímy": [
    "Real Madrid",
    "FC Barcelona",
    "Manchester United",
    "Liverpool",
    "Chelsea",
    "Arsenal",
    "Manchester City",
    "Bayern Mníchov",
    "PSG",
    "Juventus",
    "Inter Miláno",
    "AC Miláno",
    "LA Lakers",
    "Golden State Warriors",
    "Boston Celtics",
    "Chicago Bulls",
    "New York Yankees",
    "Ferrari",
    "Red Bull Racing",
    "McLaren"
],

"🎻 Hudobné nástroje": [
    "Gitara",
    "Klavír",
    "Husle",
    "Violončelo",
    "Kontrabas",
    "Bicie",
    "Saxofón",
    "Trúbka",
    "Trombón",
    "Klarinet",
    "Hoboj",
    "Flauta",
    "Harfa",
    "Akordeón",
    "Ukulele",
    "Banjo",
    "Mandolína",
    "Organ",
    "Syntetizátor",
    "Baskytara"
],

"📚 Názvy kníh": [
    "Harry Potter",
    "Pán prsteňov",
    "Malý princ",
    "1984",
    "Farma zvierat",
    "Hobit",
    "Duna",
    "Alchymista",
    "Da Vinciho kód",
    "Anna Karenina",
    "Zločin a trest",
    "Pýcha a predsudok",
    "Veľký Gatsby",
    "Moby Dick",
    "Odviate vetrom",
    "Hry o život",
    "Twilight",
    "Metro 2033",
    "Zaklínač",
    "Sherlock Holmes"
],

"🦒 Zvieratá v ZOO": [
    "Slon",
    "Žirafa",
    "Lev",
    "Tiger",
    "Zebra",
    "Nosorožec",
    "Hroch",
    "Gorila",
    "Šimpanz",
    "Orangutan",
    "Panda",
    "Koala",
    "Kengura",
    "Plameniak",
    "Tučniak",
    "Surikata",
    "Gepard",
    "Jaguár",
    "Tapír",
    "Lemur"
],

"🇪🇺 Hlavné mestá Európy": [
    "Bratislava",
    "Praha",
    "Viedeň",
    "Budapešť",
    "Varšava",
    "Berlín",
    "Paríž",
    "Londýn",
    "Madrid",
    "Rím",
    "Lisabon",
    "Amsterdam",
    "Brusel",
    "Kodaň",
    "Oslo",
    "Štokholm",
    "Helsinki",
    "Atény",
    "Dublin",
    "Záhreb"
],

"🚌 Spôsoby dopravy": [
    "Auto",
    "Autobus",
    "Vlak",
    "Električka",
    "Metro",
    "Trolejbus",
    "Motorka",
    "Bicykel",
    "Kolobežka",
    "Loď",
    "Trajekt",
    "Plachetnica",
    "Lietadlo",
    "Helikoptéra",
    "Balón",
    "Lanovka",
    "Ponorka",
    "Kamión",
    "Taxi",
    "Formula 1"
],

"🏠 Časti domu": [
    "Kuchyňa",
    "Obývačka",
    "Spálňa",
    "Kúpeľňa",
    "Toaleta",
    "Chodba",
    "Balkón",
    "Terasa",
    "Garáž",
    "Pivnica",
    "Podkrovie",
    "Schody",
    "Strecha",
    "Okno",
    "Dvere",
    "Komín",
    "Záhrada",
    "Plot",
    "Bazén",
    "Špajza"
],

"📅 Mesiace v roku": [
    "Január",
    "Február",
    "Marec",
    "Apríl",
    "Máj",
    "Jún",
    "Júl",
    "August",
    "September",
    "Október",
    "November",
    "December"
],

"🌶️ Druhy korenia": [
    "Čierne korenie",
    "Biele korenie",
    "Paprika",
    "Škorica",
    "Muškátový oriešok",
    "Kurkuma",
    "Kari",
    "Rasca",
    "Kmín",
    "Oregano",
    "Bazalka",
    "Tymián",
    "Rozmarín",
    "Klinčeky",
    "Vanilka",
    "Aníz",
    "Fenikel",
    "Zázvor",
    "Chilli",
    "Šafran"
],

"🏅 Názvy športov": [
    "Futbal",
    "Basketbal",
    "Tenis",
    "Hokej",
    "Golf",
    "Box",
    "MMA",
    "Judo",
    "Karate",
    "Taekwondo",
    "Plávanie",
    "Atletika",
    "Gymnastika",
    "Badminton",
    "Volejbal",
    "Rugby",
    "Baseball",
    "Curling",
    "Šerm",
    "Triatlon"
],

"✏️ Kancelárske potreby": [
    "Pero",
    "Ceruzka",
    "Fixka",
    "Zvýrazňovač",
    "Pravítko",
    "Nožnice",
    "Zošívačka",
    "Lepiaca páska",
    "Lepidlo",
    "Papier",
    "Zošit",
    "Blok",
    "Obálka",
    "Šanón",
    "Spinky",
    "Guma",
    "Strúhadlo",
    "Diár",
    "Kalendár",
    "Kalkulačka"
],

"🪴 Náradie do záhrady": [
    "Lopata",
    "Rýľ",
    "Hrable",
    "Motyka",
    "Krhla",
    "Hadica",
    "Kosačka",
    "Nožnice na živý plot",
    "Sekera",
    "Pílka",
    "Fúrik",
    "Vidly",
    "Kultivátor",
    "Postrekovač",
    "Záhradnícke rukavice",
    "Nožnice",
    "Rebrík",
    "Kompostér",
    "Kvetináč",
    "Sadenica"
],

"🏛️ Historické obdobia": [
    "Pravek",
    "Starovek",
    "Antika",
    "Stredovek",
    "Renesancia",
    "Barok",
    "Klasicizmus",
    "Osvietenstvo",
    "Priemyselná revolúcia",
    "Moderná doba",
    "Prvá svetová vojna",
    "Druhá svetová vojna",
    "Studená vojna",
    "Súčasnosť"
],

"⚛️ Prvky periodickej tabuľky": [
    "Vodík",
    "Hélium",
    "Lítium",
    "Uhlík",
    "Dusík",
    "Kyslík",
    "Sodík",
    "Horčík",
    "Hliník",
    "Kremík",
    "Fosfor",
    "Síra",
    "Chlór",
    "Draslík",
    "Vápnik",
    "Železo",
    "Meď",
    "Striebro",
    "Zlato",
    "Urán"
],

"✍️ Spisovatelia": [
    "William Shakespeare",
    "Jules Verne",
    "Charles Dickens",
    "Lev Nikolajevič Tolstoj",
    "Fjodor Dostojevskij",
    "Ernest Hemingway",
    "George Orwell",
    "J. K. Rowling",
    "J. R. R. Tolkien",
    "Stephen King",
    "Agatha Christie",
    "Jane Austen",
    "Victor Hugo",
    "Franz Kafka",
    "Edgar Allan Poe",
    "Arthur Conan Doyle",
    "Dan Brown",
    "Paulo Coelho",
    "Martin Kukučín",
    "Pavol Országh Hviezdoslav"
],
}
