CATEGORIES = {
    "🎬 Filmy & Seriály": [
        "Titanic", "Avatar", "Harry Potter", "Hra o tróny", "Shrek",
        "Lev kráľ", "Spiderman", "Batman", "Joker", "Inception",
        "Interstellar", "Squid Game", "Stranger Things", "Breaking Bad",
        "Frozen", "Piráti z Karibiku", "Pán prsteňov", "La La Land",
        "Forrest Gump", "The Office", "Friends", "Peaky Blinders",
        "Money Heist", "Wednesday", "Ted Lasso", "Succession",
        "The Crown", "Black Mirror", "Narcos", "Mandalorian",
        "Top Gun", "Gladiátor", "Matrix", "Jurassic Park",
        "Hviezdne vojny", "Avengers", "Muž so železnou maskou",
        "Bohemian Rhapsody", "Elvis", "Barbie",
    ],
    "🌍 Celebrities": [
        "Elon Musk", "Beyoncé", "Taylor Swift", "Cristiano Ronaldo",
        "Lionel Messi", "Kim Kardashian", "Rihanna", "Billie Eilish",
        "Justin Bieber", "Adele", "Lady Gaga", "Drake", "Eminem",
        "Will Smith", "Leonardo DiCaprio", "Angelina Jolie",
        "Dwayne Johnson", "Ariana Grande", "Ed Sheeran", "Shakira",
        "Zendaya", "Harry Styles", "Bad Bunny", "Cardi B",
        "Jeff Bezos", "Bill Gates", "Mark Zuckerberg", "Steve Jobs",
        "Barack Obama", "Oprah Winfrey", "Ellen DeGeneres",
        "Keanu Reeves", "Tom Hanks", "Meryl Streep", "Ryan Reynolds",
        "Jennifer Aniston", "Brad Pitt", "Scarlett Johansson",
        "Margot Robbie", "Timothée Chalamet", "Kylie Jenner",
    ],
    "🐘 Zvieratá": [
        "Slon", "Žirafa", "Tučniak", "Krokodíl", "Medveď",
        "Lev", "Tiger", "Gorila", "Delfín", "Morský koník",
        "Pštros", "Flamingo", "Koala", "Lenivec", "Gepard",
        "Hroch", "Nosorožec", "Vlk", "Líška", "Zajac",
        "Panda", "Orangutan", "Kapibara", "Mravenečník", "Jaguár",
        "Orka", "Žralok", "Chobotnica", "Medúza", "Morský lev",
        "Sokol", "Páv", "Tukan", "Kolibrík", "Ara",
        "Komodo varan", "Iguana", "Axolotl", "Tardigrada", "Platypus",
    ],
    "🍕 Jedlo": [
        "Pizza", "Sushi", "Burger", "Tacos", "Špagety",
        "Croissant", "Palačinky", "Zmrzlina", "Čokoláda", "Bagel",
        "Ramen", "Hummus", "Guacamole", "Tiramisu", "Fondue",
        "Paella", "Gyros", "Rizoto", "Lasagne", "Waffle",
        "Dim sum", "Pho", "Bibimbap", "Shawarma", "Falafel",
        "Nachos", "Bruschetta", "Ceviche", "Moussaka", "Pierogi",
        "Bryndzové halušky", "Langoše", "Trdelník", "Kürtőskalács",
        "Macaron", "Churros", "Baklava", "Mochi", "Poke bowl",
    ],
    "🏆 Šport": [
        "Futbal", "Tenis", "Basketbal", "Plávanie", "Atletika",
        "Cyklistika", "Lyžovanie", "Box", "Volejbal", "Golf",
        "Rugby", "Kriket", "Surfovanie", "Snowboard", "Vzpieranie",
        "Karate", "Judo", "Biatlon", "Skoky na lyžiach", "Stolný tenis",
        "Šerm", "Lukostrelba", "Triatlon", "Moderná gymnastika",
        "Skoky do vody", "Sánkovanie", "Curling", "Plachtenie",
        "Americký futbal", "Baseball", "Lacrosse", "Polo",
        "Ľadový hokej", "Inline korčuľovanie", "Skateboard", "Parkour",
        "Horolezectvo", "Padák", "Wingsuit", "Freediving",
    ],
    "🇸🇰 Slovensko": [
        "Tatry", "Bratislava", "Košice", "Bryndzové halušky", "Čičmany",
        "Vlkolínec", "Bojnice", "Devín", "Jánošík", "Orava",
        "Východná", "Demänovka", "Kriváň", "Dunaj", "Váh",
        "Spišský hrad", "Liptov", "Záhorie", "Šariš", "Tokaj",
        "Banská Bystrica", "Žilina", "Prešov", "Nitra", "Trnava",
        "Trenčín", "Poprad", "Bardejov", "Levoča", "Kežmarok",
        "Dobšinská ľadová jaskyňa", "Slovenský raj", "Muránska planina",
        "Babia hora", "Gerlachovský štít", "Slavín", "Michal Šimečka",
        "Milan Rastislav Štefánik", "Ľudovít Štúr", "Alexander Dubček",
    ],
    "💻 IT & Technológie": [
        "Internet", "Umelá inteligencia", "Blockchain", "Cloud",
        "Cybersecurity", "Big Data", "Machine Learning", "Python",
        "JavaScript", "Linux", "GitHub", "Docker", "Kubernetes",
        "ChatGPT", "Tesla", "SpaceX", "iPhone", "Android",
        "Wi-Fi", "Bluetooth", "USB", "Procesor", "GPU",
        "Serverová farma", "Firewall", "VPN", "API", "Database",
        "Open source", "Startup", "Silicon Valley", "App Store",
        "Streamlit", "TensorFlow", "React", "TypeScript", "Agile",
        "Scrum", "DevOps", "Metaverse", "NFT", "Kvantový počítač",
    ],
    "📜 História": [
        "Staroveký Rím", "Napoleón Bonaparte", "Kleopatra", "Vikingovia",
        "Stredovek", "Renesancia", "Druhá svetová vojna", "Studená vojna",
        "Francúzska revolúcia", "Americká revolúcia", "Kolumbovanie",
        "Veľká čínska múr", "Pyramídy", "Koloseum", "Trójska vojna",
        "Alexander Veľký", "Džingischán", "Atila", "Juliusz Cézar",
        "Mária Terézia", "Habsburgovci", "Osmanská ríša", "Aztékovia",
        "Inkovia", "Majovia", "Rímska ríša", "Byzantská ríša",
        "Zlatá horda", "Magna Carta", "Gutenbergova biblia",
        "Prvá svetová vojna", "Holokaust", "Berlínsky múr",
        "Apollo 11", "Hirošima", "Titanic", "Ruská revolúcia",
    ],
    "🗺️ Geografia": [
        "Amazon", "Sahara", "Everest", "Mariana priekopa", "Nílska delta",
        "Antarktída", "Arktída", "Sibirská tajga", "Grand Canyon",
        "Victoria Falls", "Mŕtve more", "Bajkalské jazero",
        "Himaláje", "Alpy", "Kordillery", "Ural", "Kaukaz",
        "Mississippi", "Volga", "Níl", "Kongo", "Mekong",
        "Tichý oceán", "Atlantický oceán", "Indický oceán",
        "Stredozemné more", "Červené more", "Arabské more",
        "Amazónsky prales", "Savana", "Tundra", "Step",
        "Coral reef", "Gejzír", "Sopka", "Tsunami", "Tornádo",
        "Polárna žiara", "Monsún", "El Niño",
    ],
    "🏙️ Hlavné mestá": [
        "Paríž", "Londýn", "Berlín", "Madrid", "Rím",
        "Atény", "Viedeň", "Praha", "Varšava", "Budapešť",
        "Brusel", "Amsterdam", "Štokholm", "Oslo", "Kodaň",
        "Helsinki", "Lisabon", "Dublin", "Záhreb", "Bukurešť",
        "Sofía", "Belehrad", "Kyjev", "Moskva", "Minsk",
        "Washington D.C.", "Ottawa", "Mexico City", "Buenos Aires", "Brasília",
        "Tokio", "Peking", "Soul", "Bangkok", "Jakarta",
        "Nairobi", "Káhira", "Pretória", "Abuja", "Addis Abeba",
        "Canberra", "Wellington", "Lima", "Bogotá", "Santiago",
    ],
    "🔬 Veda & Príroda": [
        "Gravitácia", "Evolúcia", "DNA", "Fotosyntéza", "Osmóza",
        "Periodická tabuľka", "Atóm", "Čierna diera", "Supernova",
        "Fotoelektrický jav", "Relativita", "Kvantová fyzika",
        "Termodinámika", "Elektromagnetizmus", "Jadrová fúzia",
        "Klonování", "CRISPR", "Vakcína", "Antibiotiká", "Penicilín",
        "Gravitačné vlny", "Temná hmota", "Multiverse", "Wormhole",
        "Schrödingerova mačka", "Heisenbergov princíp",
        "Darwinova teória", "Mendelove zákony", "Newtonove zákony",
        "Archimédov zákon", "Pythagorova veta", "Eulerovo číslo",
        "Fibonacciho postupnosť", "Chaos theory", "Fraktál",
    ],
    "🎵 Hudba": [
        "Beatles", "Rolling Stones", "Queen", "ABBA", "Michael Jackson",
        "Elvis Presley", "Bob Dylan", "Jimi Hendrix", "Led Zeppelin",
        "Pink Floyd", "Nirvana", "U2", "Coldplay", "Radiohead",
        "Daft Punk", "Madonna", "Whitney Houston", "Mariah Carey",
        "Frank Sinatra", "Louis Armstrong", "Miles Davis", "Bob Marley",
        "Mozart", "Beethoven", "Bach", "Chopin", "Vivaldi",
        "Gitara", "Husle", "Klavír", "Bubnová súprava", "Saxofón",
        "Hip-hop", "Jazz", "Klasická hudba", "Reggae", "Techno",
        "Grammy", "Woodstock", "Eurovision", "Coachella",
    ],
}

# Appended category
CATEGORIES["⚽ Futbalové fakty"] = [
    "Pelé", "Maradona", "Ronaldo", "Messi", "Zidane",
    "Ronaldinho", "Beckham", "Platini", "Cruyff", "Puskas",
    "FC Barcelona", "Real Madrid", "Manchester United", "Bayern Mníchov", "Juventus",
    "Liverpool", "Chelsea", "PSG", "AC Miláno", "Inter Miláno",
    "FIFA World Cup", "UEFA Champions League", "El Clásico", "Derby della Madonnina",
    "Zlatá lopta", "Hat-trick", "Offside", "Penalta", "Červená karta",
    "Wembley", "Maracanã", "Camp Nou", "San Siro", "Anfield",
    "Brazília 5x majster sveta", "Nemecko 4x majster sveta", "Najdrahší hráč Neymar",
    "Prvé MS 1930 Uruguay", "Goal of the century Maradona", "Hand of God",
    "Gól za 11 sekúnd", "Najvyššia prehra 31:0 Samoa", "Hráč bez nôh Marcelo",
    "VAR technológia", "Goal-line technológia", "Zlatá kopačka", "Treble",
    "Najrýchlejší gól 2 sekundy", "Ronaldo 900 gólov", "Messi 8x Zlatá lopta",
]
